apiVersion: v1
kind: Service
metadata:
  name: snippetbox-service
spec:
  type: NodePort
  selector:
    name: snippetbox-pod
    app: snippetbox
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30000
