apiVersion: apps/v1
kind: Deployment
metadata:
  name: snippetbox-deploy
  labels:
    name: snippetbox-deploy
    app: snippetbox
spec:
  replicas: 1
  selector:
    matchLabels:
      name: snippetbox-pod
      app: snippetbox
  template:
    metadata:
      name: snippetbox-pod
      labels:
        name: snippetbox-pod
        app: snippetbox
    spec:
      containers:
      - name: snippetbox
        image: diasraibek/snippetbox:1.0
        resources:  
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: db_passwd
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: snippetbox-configmap
              key: db_host
        args: ["-addr", ":4000", "-dsn", "$(DB_USER):$(DB_PASSWORD)@tcp($(DB_HOST))/snippetbox?parseTime=true"]
        livenessProbe:
          tcpSocket:
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:  
          tcpSocket:
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
