apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: mysql-service
    app: snippetbox
spec:
  type: {{ .Values.service.db.type }}
  selector:
    name: mysql-pod
    app: snippetbox
  ports:
    - port: {{ .Values.service.db.port }}
      targetPort: {{ .Values.service.db.targetPort }}
