apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secret.name }}
type: {{ .Values.database.secret.type }}
data:
  db_user: {{ .Values.database.secret.data.db_user }}
  db_passwd: {{ .Values.database.secret.data.db_passwd }}
